name:                tesseract-bindings
version:             0.1.0.0
github:              "githubuser/tesseract-bindings"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tesseract-bindings#readme>

dependencies:
- base >= 4.7 && < 5
- protolude
- bytestring
- text
- containers

default-extensions:
  - AllowAmbiguousTypes
  - BlockArguments
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - DeriveFunctor
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - InstanceSigs
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PolyKinds
  - PartialTypeSignatures
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TransformListComp
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TupleSections
  - TypeSynonymInstances
  - UndecidableInstances
  - ViewPatterns


library:
  source-dirs: src

executables:
  tesseract-bindings-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tesseract-bindings

tests:
  tesseract-bindings-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tesseract-bindings
